package com.voyantra.servlet;

import java.io.IOException;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.voyantra.db.DBConnection;
import javax.servlet.annotation.WebServlet;
@WebServlet("/DownloadPdfServlet")

public class DownloadPdfServlet extends HttpServlet {

    private static final long serialVersionUID = 1L;

    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession(false);
        if (session == null || session.getAttribute("userId") == null) {
            response.sendRedirect("login.html");
            return;
        }
        int userId = (int) session.getAttribute("userId");

        String tripIdStr = request.getParameter("tripId");
        if (tripIdStr == null) {
            response.sendRedirect("dashboard.jsp");
            return;
        }
        int tripId = Integer.parseInt(tripIdStr);

        try (Connection conn = DBConnection.getConnection()) {

            if (conn == null) {
                response.getWriter().println("Database connection failed.");
                return;
            }

            String tripSql = "SELECT destination, budget, num_days, travel_style, interests "
                            + "FROM trips WHERE trip_id = ? AND user_id = ?";
            PreparedStatement tripStmt = conn.prepareStatement(tripSql);
            tripStmt.setInt(1, tripId);
            tripStmt.setInt(2, userId);
            ResultSet tripRs = tripStmt.executeQuery();

            if (!tripRs.next()) {
                response.getWriter().println("Trip not found.");
                return;
            }

            String destination = tripRs.getString("destination");
            double budget = tripRs.getDouble("budget");
            int numDays = tripRs.getInt("num_days");
            String travelStyle = tripRs.getString("travel_style");
            String interests = tripRs.getString("interests");

            response.setContentType("application/pdf");
            response.setHeader("Content-Disposition",
                    "attachment; filename=\"" + destination.replaceAll("[^a-zA-Z0-9]", "_") + "_itinerary.pdf\"");

            Document document = new Document(PageSize.A4, 40, 40, 50, 50);
            OutputStream out = response.getOutputStream();
            PdfWriter.getInstance(document, out);
            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22);
            Font headingFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
            Font labelFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11);
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 11);

            Paragraph title = new Paragraph(destination + " - Trip Itinerary", titleFont);
            title.setSpacingAfter(4);
            document.add(title);

            Paragraph brand = new Paragraph("Generated by Voyantra AI Travel Planner", normalFont);
            brand.setSpacingAfter(20);
            document.add(brand);

            document.add(new Paragraph("Budget: Rs " + (int) budget, normalFont));
            document.add(new Paragraph("Duration: " + numDays + " days", normalFont));
            document.add(new Paragraph("Travel style: " + travelStyle, normalFont));
            Paragraph interestsPara = new Paragraph("Interests: " + interests, normalFont);
            interestsPara.setSpacingAfter(20);
            document.add(interestsPara);

            String itinSql = "SELECT day_number, activities, food_suggestions, hotel_suggestion, weather_info "
                            + "FROM itineraries WHERE trip_id = ? ORDER BY day_number ASC";
            PreparedStatement itinStmt = conn.prepareStatement(itinSql);
            itinStmt.setInt(1, tripId);
            ResultSet itinRs = itinStmt.executeQuery();

            boolean anyDay = false;
            while (itinRs.next()) {
                anyDay = true;
                Paragraph dayHeading = new Paragraph("Day " + itinRs.getInt("day_number"), headingFont);
                dayHeading.setSpacingBefore(14);
                dayHeading.setSpacingAfter(6);
                document.add(dayHeading);

                document.add(makeLine("Activities: ", itinRs.getString("activities"), labelFont, normalFont));
                document.add(makeLine("Food: ", itinRs.getString("food_suggestions"), labelFont, normalFont));
                document.add(makeLine("Stay: ", itinRs.getString("hotel_suggestion"), labelFont, normalFont));
                document.add(makeLine("Weather: ", itinRs.getString("weather_info"), labelFont, normalFont));
            }

            if (!anyDay) {
                document.add(new Paragraph("No itinerary has been generated for this trip yet.", normalFont));
            }

            document.close();

        } catch (SQLException | com.itextpdf.text.DocumentException e) {
            e.printStackTrace();
            try {
                response.getWriter().println("Could not generate PDF: " + e.getMessage());
            } catch (IOException ignored) {}
        }
    }

    private Paragraph makeLine(String label, String value, Font labelFont, Font normalFont) {
        com.itextpdf.text.Chunk labelChunk = new com.itextpdf.text.Chunk(label, labelFont);
        com.itextpdf.text.Chunk valueChunk = new com.itextpdf.text.Chunk(value == null ? "" : value, normalFont);
        Paragraph p = new Paragraph();
        p.add(labelChunk);
        p.add(valueChunk);
        p.setSpacingAfter(4);
        p.setAlignment(Element.ALIGN_LEFT);
        return p;
    }
}